<?php

?>
<div style="background:#EAF0EE;border:1px solid #CCCCCC;margin-bottom:10px;padding:11px 0 0 10px;">
    <h4>
        <img width="224px" height="60px" src="https://lucy-website.s3.amazonaws.com/Logo_lucy.png"/><br><br>
        <div style="padding-left: 30px;">
            <p> <strong style="color:#EA7601;"><?php echo __('LucyMail v') ?><?php echo $this->getVersion() ?><?php echo __(' by') ?></strong> <a target="_blank" href="http://lucy.com.ng"><strong>lucy</strong></a></p>
            <p><?php echo __('Need help? See our ') ?><a href="http://wiki.lucy.com.ng/installation" target="_blank"><?php echo __('Wiki') ?></a><?php echo __(' or browse our ') ?><a href="http://lucy.com.ng/forums/view/1" target="_blank"><?php echo __('support forums') ?></a><?php echo __(' Got feedback? ') ?><a href="mailto:mailchimp@lucy-desk.zendesk.com?Subject=MailChimp Version <?php echo $this->getVersion()?>"><?php echo __('Email us') ?></a></p>
            <p><?php echo __('You can find more extension in our ') ?><a href="http://store.lucy.com.ng" target="_blank"><?php echo __('Store') ?></a></p>
            <h3><a style="padding-top: 5px;padding-bottom:5px;padding-left: 30px;padding-right: 30px;background-color:#EB5202 ;color:white;font-weight: bold" href="http://www.mailchimp.com/signup?pid=lucy&source=website" target="_blank"><?php echo __('Support LucyMail, Subscribe for a free MailChimp Account!') ?></a> </h3>
        </div>
    </h4>
</div>